name: brats2024_gli
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anaconda-anon-usage=0.4.4
  - archspec=0.2.3
  - boltons=23.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - charset-normalizer=2.0.4
  - conda=24.11.3
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=24.1.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - distro=1.9.0
  - expat=2.6.2
  - fmt=9.1.0
  - frozendict=2.4.7
  - icu=73.1
  - idna=3.7
  - jsonpatch=1.33
  - jsonpointer=2.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libarchive=3.6.2
  - libcurl=8.7.1
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.57.0
  - libsolv=0.7.24
  - libssh2=1.11.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - menuinst=2.0.2
  - ncurses=6.4
  - openssl=3.6.0
  - packaging=23.2
  - pcre2=10.42
  - pip=24.0
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.12.3
  - python_abi=3.12
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - ripgrep=15.1.0
  - ruamel.yaml=0.17.21
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - truststore=0.8.0
  - wheel=0.43.0
  - xz=5.4.6
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - acvl-utils==0.2.5
      - alembic==1.17.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - argparse==1.4.0
      - arrow==1.3.0
      - astor==0.8.1
      - asttokens==2.4.1
      - async-lru==2.0.4
      - asyncio-atexit==1.0.1
      - attrs==24.2.0
      - authlib==1.6.5
      - babel==2.16.0
      - batchgenerators==0.25.1
      - batchgeneratorsv2==0.3.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - blinker==1.9.0
      - blosc2==3.12.2
      - cachetools==6.2.1
      - cffi==2.0.0
      - clearml==2.0.3rc0
      - click==8.3.0
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - colorlog==6.10.1
      - comm==0.2.2
      - connected-components-3d==3.26.1
      - contourpy==1.3.1
      - crc32c==2.7.1.post0
      - cryptography==46.0.3
      - cycler==0.12.1
      - cyclopts==3.24.0
      - databricks-sdk==0.68.0
      - debugpy==1.8.9
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - dnspython==2.8.0
      - docker==7.1.0
      - docstring-parser==0.17.0
      - docutils==0.22.2
      - donfig==0.8.1.post1
      - dynamic-network-architectures==0.4.2
      - einops==0.8.1
      - email-validator==2.3.0
      - exceptiongroup==1.3.0
      - executing==2.1.0
      - fastapi==0.119.0
      - fastjsonschema==2.20.0
      - fastmcp==2.12.4
      - fft-conv-pytorch==1.2.0
      - filelock==3.11.0
      - fire==0.7.1
      - flask==3.1.2
      - flask-cors==6.0.1
      - fonttools==4.55.0
      - fqdn==1.5.1
      - fsspec==2024.10.0
      - furl==2.1.4
      - future==1.0.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.41.1
      - googleapis-common-protos==1.70.0
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - graphviz==0.21
      - greenlet==3.2.4
      - grpcio==1.68.0
      - gunicorn==23.0.0
      - h11==0.16.0
      - h5py==3.15.1
      - hf-transfer==0.1.9
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.35.3
      - humanize==4.14.0
      - imagecodecs==2025.8.2
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - ipykernel==6.29.5
      - ipython==8.29.0
      - ipywidgets==8.1.5
      - isodate==0.7.2
      - isoduration==20.11.0
      - itk==5.4.4.post1
      - itk-core==5.4.4.post1
      - itk-filtering==5.4.4.post1
      - itk-io==5.4.4.post1
      - itk-numerics==5.4.4.post1
      - itk-registration==5.4.4.post1
      - itk-segmentation==5.4.4.post1
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.5.2
      - json-tricks==3.17.3
      - json5==0.9.28
      - jsonschema==4.23.0
      - jsonschema-path==0.3.4
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.1
      - jupyterlab-language-pack-zh-cn==4.2.post3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lazy-object-proxy==1.12.0
      - lightning-utilities==0.15.2
      - linecache2==1.0.0
      - lmdb==1.7.5
      - lpips==0.1.4
      - lxml==6.0.2
      - mako==1.3.10
      - markdown==3.7
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mcp==1.18.0
      - mdurl==0.1.2
      - mistune==3.0.2
      - ml-dtypes==0.5.3
      - mlflow==3.5.0
      - mlflow-skinny==3.5.0
      - mlflow-tracing==3.5.0
      - monai==1.5.1
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - ndindex==1.10.1
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nibabel==5.3.3
      - ninja==1.13.0
      - nni==3.0
      - nnunetv2==2.6.2
      - notebook-shim==0.2.4
      - numcodecs==0.16.3
      - numexpr==2.14.1
      - numpy==2.1.3
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - onnx==1.19.1
      - openapi-core==0.19.5
      - openapi-pydantic==0.5.1
      - openapi-schema-validator==0.6.3
      - openapi-spec-validator==0.7.2
      - opencv-python==4.12.0.88
      - openslide-bin==4.0.0.8
      - openslide-python==1.4.2
      - opentelemetry-api==1.37.0
      - opentelemetry-exporter-otlp-proto-common==1.37.0
      - opentelemetry-exporter-otlp-proto-http==1.37.0
      - opentelemetry-instrumentation==0.58b0
      - opentelemetry-instrumentation-httpx==0.58b0
      - opentelemetry-instrumentation-requests==0.58b0
      - opentelemetry-instrumentation-threading==0.58b0
      - opentelemetry-instrumentation-urllib==0.58b0
      - opentelemetry-proto==1.37.0
      - opentelemetry-sdk==1.37.0
      - opentelemetry-semantic-conventions==0.58b0
      - opentelemetry-util-http==0.58b0
      - optuna==4.5.0
      - orderedmultidict==1.0.1
      - overrides==7.7.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parse==1.20.2
      - parso==0.8.4
      - pathable==0.4.4
      - pathlib2==2.3.7.post1
      - pexpect==4.9.0
      - pillow==11.0.0
      - prettytable==3.16.0
      - prometheus-client==0.21.0
      - prompt-toolkit==3.0.48
      - protobuf==5.28.3
      - psutil==5.9.8
      - ptflops==0.7.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyamg==5.2.1
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.2
      - pydantic-core==2.41.4
      - pydantic-settings==2.11.0
      - pydicom==3.0.1
      - pygments==2.18.0
      - pyjwt==2.10.1
      - pynrrd==1.1.3
      - pyparsing==3.2.0
      - pyperclip==1.11.0
      - python-dateutil==2.9.0.post0
      - python-docx==1.2.0
      - python-dotenv==1.1.1
      - python-json-logger==2.0.7
      - python-multipart==0.0.20
      - pythonwebhdfs==0.2.3
      - pytorch-ignite==0.4.11
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==26.2.0
      - referencing==0.35.1
      - requests==2.32.5
      - responses==0.25.8
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.2.0
      - rich-rst==1.3.2
      - rpds-py==0.21.0
      - rsa==4.9.1
      - safetensors==0.6.2
      - schema==0.7.8
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - shellingham==1.5.4
      - simpleitk==2.5.2
      - simplejson==3.20.2
      - six==1.16.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==2.0.44
      - sqlparse==0.5.3
      - sse-starlette==3.0.2
      - stack-data==0.6.3
      - starlette==0.48.0
      - supervisor==4.2.5
      - sympy==1.13.1
      - synapseclient==4.10.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - termcolor==3.1.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tifffile==2025.10.4
      - timm==1.0.20
      - tinycss2==1.4.0
      - torch==2.5.1+cu124
      - torchaudio==2.5.1+cu118
      - torchio==0.20.23
      - torchmetrics==1.8.2
      - torchvision==0.20.1+cu124
      - tornado==6.4.2
      - tqdm==4.67.1
      - traceback2==1.4.0
      - traitlets==5.14.3
      - triton==3.1.0
      - typeguard==4.1.2
      - typer==0.19.2
      - types-python-dateutil==2.9.0.20241003
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - unittest2==1.1.0
      - uri-template==1.3.0
      - urllib3==1.26.20
      - uvicorn==0.37.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==15.0.1
      - werkzeug==3.1.1
      - widgetsnbextension==4.0.13
      - wrapt==1.17.3
      - yacs==0.1.8
      - zarr==3.1.3
      - zipp==3.23.0
prefix: /root/miniconda3
