seed: 1337
data:
  roi_root: data/preprocessed/npy_roi128_jit8_v1
  splits_dir: data/splits
  batch_size: 2
  num_workers: 8
  pin_memory: true
model:
  in_channels: 4
  out_channels: 5
  base_channels: 48
  dropout: 0.0
train:
  epochs: 240
  lr: 0.00015
  weight_decay: 1.0e-05
  amp: true
  grad_clip: 1.0
  val_every: 1
  early_stop_patience: 40
loss:
  dice_weight: 1.0
  focal_weight: 1.0
  focal_gamma: 2.0
  class_weights: null
augment:
  enable: true
  flip_prob: 0.5
  rot90_prob: 0.25
  translate_max: 0
  translate_prob: 0.0
  intensity_shift: 0.1
  intensity_scale: 0.1
  noise_std: 0.05
metrics:
  main: mean_wt_tc_et
  tc_includes_rc: false
run:
  name: auto
